### ISSUE TITLE
cmd-key-happy stops working

### ISSUE THREAD

**Issue by mhorowitz** [andymcd/cmd-key-happy#8]
This is a crappy bug report, but since it's happened to me twice, I figured I'd report it, and hopefully it would ring some bells.  Running Lion, cmd-key-happy is working just fine, but at some point, cmd and option revert to their stock meaning. None of the following fix it:
- launchctl stop/start
- launchctl stop, run in shell
- quit/re-run Terminal
- sleep/wake
- switch to login window and back

I need to do a full shutdown and restart of the machine, then everything is back to normal.  I realized I have not tried logging out and back in again.  I will do that next time, although this is as destructive to my running session as a restart, so it's not a great answer.

I regularly sleep and resume my laptop, and connect and disconnect an external keyboard and monitor, if any of these could be a problem.

Is there anything I can try?

**Comment by pjlegato** [comment]
I just experienced this issue again today, and saw another case last week. In both cases, closing Chrome immediately solved the problem.

**Comment by frobware** [comment]
> I just experienced this issue again today, and saw another case last week. In both cases, closing Chrome immediately solved the problem.

It is difficult for me to now look at this as I no longer have a working Mac. :-/
